# Generated by Django 5.1.3 on 2024-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_adminprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="products_image/"),
        ),
    ]
